import { Injectable, BadRequestException, NotFoundException, Logger, forwardRef, Inject } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'crypto';
import { createServiceSupabaseClient } from '../shared/supabase.client';
import { WalletService } from '../wallet/wallet.service';
import { WalletTransactionType } from '../wallet/constants/transaction-types';
import { ChatService } from '../chat/chat.service';
import { NotificationHelperService } from '../notifications/notification-helper.service';
import { MessageType } from '../chat/dto/chat.dto';
import { EmailService } from '../auth/email.service';
import {
  PurchaseGiftCardDto,
  GiftCardResponse,
  ClaimResponse,
  RedeemResponse,
  BalanceResponse,
} from './dto/purchase-gift-card.dto';
import { AdminCreateGiftCardDto } from './dto/admin-create-gift-card.dto';
import { GiftCard } from './entities/gift-card.entity';

@Injectable()
export class GiftCardService {
  private readonly logger = new Logger(GiftCardService.name);
  private supabase;
  private readonly adminGiftWalletId: string;
  private readonly platformWalletId: string;
  
  constructor(
    private configService: ConfigService,
    private walletService: WalletService,
    @Inject(forwardRef(() => ChatService))
    private chatService: ChatService,
    private notificationHelper: NotificationHelperService,
    private emailService: EmailService,
  ) {
    this.supabase = createServiceSupabaseClient(this.configService);
    this.adminGiftWalletId = this.configService.get<string>('PLATFORM_GIFT_WALLET_USER_ID', '00000000-0000-4000-8000-000000000003');
    this.platformWalletId = this.configService.get<string>('PLATFORM_USER_ID', '00000000-0000-4000-8000-000000000002');
  }
  
  async purchaseGiftCard(userId: string, dto: PurchaseGiftCardDto): Promise<GiftCardResponse> {
    this.logger.log(`Processing gift card purchase for user ${userId}`);
    
    // 1. Validate recipient if provided
    let recipientUserId: string | null = null;
    if (dto.recipientUsername) {
      recipientUserId = await this.validateAndGetRecipientId(dto.recipientUsername);
    }
    
    // 2. Determine delivery method
    const deliveryMethod = this.determineDeliveryMethod(dto);
    
    // 3. Check user wallet balance
    const wallet = await this.walletService.getWallet(userId);
    if (wallet.availableBalance < dto.amount) {
      throw new BadRequestException(`Insufficient wallet balance. Required: ${dto.amount} FRETI, Available: ${wallet.availableBalance} FRETI`);
    }
    
    // 4. ✅ ATOMIC FIX: One RPC debits the buyer, inserts the gift_cards
    // row (card_number/pin/claim_code generated by DB triggers), credits
    // the marketing/reserve wallet, and logs the gift_card_transactions
    // audit row in a single Postgres transaction. If any part fails, the
    // whole transaction rolls back, eliminating the previous "buyer
    // debited but card or reserve not created" saga window.
    const purchaseReferenceId = randomUUID();

    const { data: purchaseResult, error: purchaseRpcError } = await this.supabase.rpc(
      'purchase_gift_card_atomic',
      {
        p_purchaser_id: userId,
        p_admin_user_id: this.adminGiftWalletId,
        p_amount: dto.amount,
        p_design_id: dto.designId,
        p_recipient_user_id: recipientUserId,
        p_recipient_username: dto.recipientUsername,
        p_recipient_email: dto.recipientEmail,
        p_recipient_phone: dto.recipientPhone,
        p_delivery_method: deliveryMethod,
        p_expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        p_reference_id: purchaseReferenceId,
      }
    );

    if (purchaseRpcError) {
      this.logger.error(`[GiftCardsService] purchase_gift_card_atomic RPC error: ${purchaseRpcError.message}`);
      throw new BadRequestException(`Gift card purchase failed: ${purchaseRpcError.message}`);
    }

    if (!purchaseResult || !purchaseResult.success) {
      this.logger.error(`[GiftCardsService] purchase_gift_card_atomic returned failure: ${purchaseResult?.error || 'Unknown'}`);
      throw new BadRequestException(purchaseResult?.error || 'Gift card purchase failed');
    }

    if (purchaseResult.already_processed) {
      this.logger.warn(`[GiftCardsService] ⚠️ IDEMPOTENT: Duplicate gift card purchase detected and prevented for user ${userId}, reference: ${purchaseReferenceId}`);
    } else {
      this.logger.log(`[GiftCardsService] ✅ Atomic gift card purchase successful: ${purchaseResult.transaction_id} for user ${userId}`);
    }

    // 5. Fetch the created/returned card with design data for the response.
    //    The RPC returns the raw gift_card row; we still need the design
    //    join for the email and the API response.
    const { data: giftCard, error: fetchError } = await this.supabase
      .from('gift_cards')
      .select(`
        *,
        design:gift_card_designs (
          name,
          design_url,
          preview_url
        )
      `)
      .eq('id', purchaseResult.gift_card.id)
      .single();

    if (fetchError || !giftCard) {
      this.logger.error(`[GiftCardsService] Failed to fetch created gift card: ${fetchError?.message || 'not found'}`);
      throw new BadRequestException('Failed to load created gift card');
    }
    
    // 7. Deliver gift card based on method
    let deliveryFailed = false;
    if (deliveryMethod === 'email' || deliveryMethod === 'both') {
      const emailSent = await this.sendGiftCardEmail(giftCard, dto.personalMessage);
      if (!emailSent) deliveryFailed = true;
    }
    
    if (deliveryMethod === 'chat' || deliveryMethod === 'both') {
      const chatSent = await this.sendGiftCardChatMessage(giftCard, dto.personalMessage);
      if (!chatSent) deliveryFailed = true;
    }
    
    // 8. If no recipient, auto-claim for purchaser
    const autoClaimed = !dto.recipientUsername && !dto.recipientEmail;
    if (autoClaimed) {
      await this.autoClaimForPurchaser(giftCard.id, userId);
    }
    
    // 9. Send notification to purchaser
    try {
      await this.notificationHelper.notifySystemUpdate(
        userId,
        'Gift Card Purchase Successful! 🎁',
        `You purchased a ${dto.amount} FRETI gift card`,
        { type: 'gift_card_purchased', giftCardId: giftCard.id }
      );
    } catch (error) {
      this.logger.error('Failed to send purchase notification:', error);
      // Non-critical, continue with order
    }
    
    return {
      id: giftCard.id,
      cardNumber: giftCard.card_number,
      amount: giftCard.initial_balance,
      design: {
        name: giftCard.design?.name,
        designUrl: giftCard.design?.design_url,
        previewUrl: giftCard.design?.preview_url,
      },
      deliveryMethod,
      autoClaimed,
      deliveryFailed
    };
  }
  
  private determineDeliveryMethod(dto: PurchaseGiftCardDto): string {
    if (dto.recipientUsername && dto.recipientEmail) {
      return dto.deliveryPreference || 'both';
    } else if (dto.recipientUsername) {
      return 'chat';
    } else if (dto.recipientEmail) {
      return 'email';
    }
    return 'none'; // Self-purchase
  }
  
  private async validateAndGetRecipientId(username: string): Promise<string> {
    const { data, error } = await this.supabase
      .from('user_profiles')
      .select('id')
      .eq('username', username)
      .single();
    
    if (error || !data) {
      throw new BadRequestException(`User "${username}" not found`);
    }
    
    return data.id;
  }
  
  private async sendGiftCardChatMessage(giftCard: any, personalMessage?: string): Promise<boolean> {
    try {
      // Find or create conversation between purchaser and recipient
      const conversation = await this.chatService.findOrCreateConversation(
        giftCard.purchaser_id,
        [giftCard.recipient_user_id],
        'friend',
        undefined as any // Type casting to handle parameter signature
      );
      
      // Create gift card message
      const messageData = {
        conversationId: conversation.id,
        messageType: MessageType.GIFT_CARD,
        content: personalMessage || 'Sent you a gift card! 🎁',
        metadata: {
          giftCardId: giftCard.id,
          cardNumber: giftCard.card_number.substring(12), // Last 4 digits only
          amount: giftCard.initial_balance,
          designName: giftCard.design?.name,
          designUrl: giftCard.design?.design_url,
          claimCode: giftCard.claim_code,
          status: giftCard.status,
          expiresAt: giftCard.expires_at,
          purchaserId: giftCard.purchaser_id,
          recipientUserId: giftCard.recipient_user_id,
        }
      };
      
      const messageResult = await this.chatService.sendMessage(giftCard.purchaser_id, messageData);
      
      // Update gift card with chat message reference
      if (messageResult && messageResult.id) {
        await this.supabase
          .from('gift_cards')
          .update({
            chat_message_id: messageResult.id,
            chat_sent_at: new Date().toISOString()
          })
          .eq('id', giftCard.id);
      }
      
      this.logger.log(`Gift card sent via chat to user ${giftCard.recipient_user_id}`);
      return true;
    } catch (error: any) {
      this.logger.error(`Failed to send gift card chat message: ${error.message}`);
      // Don't throw - gift card is still valid, but let the caller know delivery failed
      return false;
    }
  }
  
  private async sendGiftCardEmail(giftCard: any, personalMessage?: string): Promise<boolean> {
    try {
      const claimBaseUrl = this.configService.get<string>('GIFT_CARD_CLAIM_BASE_URL', 'https://fretiko.com/gift-cards/claim');
      const claimUrl = `${claimBaseUrl.replace(/\/$/, '')}/${giftCard.claim_code}`;
      
      // Send email using Resend
      const resendApiKey = this.configService.get<string>('RESEND_API_KEY');
      const resendFromEmail = this.configService.get<string>('RESEND_FROM_EMAIL');
      
      if (!resendApiKey || !resendFromEmail) {
        this.logger.warn('Resend configuration missing, skipping email send');
        await this.supabase
          .from('gift_cards')
          .update({
            email_sent_at: new Date().toISOString(),
            email_sent_to: giftCard.recipient_email
          })
          .eq('id', giftCard.id);
        return false;
      }
      
      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${resendApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: resendFromEmail,
          to: [giftCard.recipient_email],
          subject: 'You received a Fretiko Gift Card! 🎁',
          html: this.generateGiftCardEmailContent(giftCard, personalMessage, claimUrl),
        }),
        signal: AbortSignal.timeout(30000),
      });
      
      let emailSent = response.ok;
      if (response.ok) {
        this.logger.log(`Gift card email sent successfully to ${giftCard.recipient_email}`);
      } else {
        const result = await response.json();
        this.logger.error(`Failed to send gift card email: ${JSON.stringify(result)}`);
      }
      
      await this.supabase
        .from('gift_cards')
        .update({
          email_sent_at: new Date().toISOString(),
          email_sent_to: giftCard.recipient_email
        })
        .eq('id', giftCard.id);

      return emailSent;
    } catch (error: any) {
      this.logger.error(`Failed to send gift card email: ${error.message}`);
      // Don't throw - gift card is still valid, but let the caller know delivery failed
      return false;
    }
  }
  
  private generateGiftCardEmailContent(giftCard: any, personalMessage?: string, claimUrl?: string): string {
    const recipientName = giftCard.recipient_username || 'there';
    const amount = giftCard.initial_balance;
    const designName = giftCard.design?.name || 'Gift Card';
    const designUrl = giftCard.design?.design_url || giftCard.design?.preview_url;
    const maskedNumber = giftCard.card_number
      ? `${giftCard.card_number.slice(-4).padStart(giftCard.card_number.length, '*')}`
      : '****';

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>You received a Fretiko Gift Card!</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .container { background: #ffffff; border-radius: 16px; padding: 32px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); text-align: center; }
        .logo { font-size: 28px; font-weight: bold; color: #F39C12; margin-bottom: 8px; }
        .subtitle { color: #666; margin-bottom: 24px; }
        .card-visual {
          border-radius: 16px;
          overflow: hidden;
          margin: 24px 0;
          box-shadow: 0 6px 24px rgba(0,0,0,0.12);
        }
        .card-visual img { display: block; width: 100%; height: auto; border-radius: 16px; }
        .card-fallback { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 48px 24px; border-radius: 16px; }
        .card-amount { font-size: 42px; font-weight: bold; color: #222; margin: 8px 0; }
        .card-design { font-size: 18px; color: #555; margin: 4px 0 16px; }
        .personal-message { font-style: italic; color: #777; margin: 20px 0; padding: 0 24px; }
        .button { display: inline-block; background: #F39C12; color: white; padding: 16px 48px; text-decoration: none; border-radius: 30px; font-weight: bold; font-size: 16px; margin: 20px 0; }
        .manual-link { font-size: 12px; color: #999; margin-top: 12px; word-break: break-all; }
        .footer { margin-top: 32px; font-size: 12px; color: #999; }
        .security-note { background: #fff8e6; border: 1px solid #ffe8a8; border-radius: 10px; padding: 12px; margin-top: 20px; font-size: 13px; color: #856404; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">🎁 Fretiko</div>
        <h1>You received a Gift Card!</h1>
        <p class="subtitle">Hi ${recipientName}, someone sent you a Fretiko gift card.</p>

        ${designUrl ? `
        <div class="card-visual">
            <img src="${designUrl}" alt="${designName}" />
        </div>
        ` : `
        <div class="card-visual">
            <div class="card-fallback">
                <h2 style="margin: 0;">${designName}</h2>
                <div class="card-amount">${amount} FRETI</div>
            </div>
        </div>
        `}

        <div class="card-design">${designName}</div>
        <div class="card-amount">${amount} FRETI</div>

        ${personalMessage ? `<p class="personal-message">"${personalMessage}"</p>` : ''}

        <p style="color: #555; margin-top: 24px;">Tap the button below to claim it in the Fretiko app:</p>
        <a href="${claimUrl}" class="button">Claim Gift Card</a>

        <p class="manual-link">Or copy this link:<br>${claimUrl}</p>

        <div class="security-note">
            🔒 For security, your full gift card number and PIN are not shown here. They will be available inside the app once you claim it.
        </div>

        <div class="footer">
            <p>Gift Card Number: ${maskedNumber}</p>
            <p>If you didn't expect this gift card, please ignore this email.</p>
            <p>© 2026 Fretiko. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
    `;
  }
  
  private async autoClaimForPurchaser(giftCardId: string, userId: string): Promise<void> {
    await this.supabase
      .from('gift_cards')
      .update({
        status: 'claimed',
        recipient_user_id: userId,
        claimed_at: new Date().toISOString()
      })
      .eq('id', giftCardId);
  }

  generateGiftCardClaimLandingPage(claimCode: string): string {
    const appSchemeUrl = `fretiko://gift-cards/claim/${encodeURIComponent(claimCode)}`;
    const playStoreUrl = this.configService.get<string>('GOOGLE_PLAY_STORE_URL', 'https://play.google.com/store/apps/details?id=com.fretiko.mobile');
    const appStoreUrl = this.configService.get<string>('APP_STORE_URL', 'https://apps.apple.com/app/fretiko');

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Claim your Fretiko Gift Card</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; background: #0f172a; color: #fff; margin: 0; padding: 0; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
        .card { width: 100%; max-width: 420px; padding: 32px; text-align: center; }
        .icon { font-size: 64px; margin-bottom: 12px; }
        h1 { font-size: 24px; margin: 0 0 12px; }
        p { color: #94a3b8; font-size: 15px; margin: 0 0 24px; line-height: 1.5; }
        .code { background: rgba(255,255,255,0.08); border-radius: 12px; padding: 12px 20px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 18px; color: #f39c12; margin: 16px 0; display: inline-block; letter-spacing: 2px; }
        .btn { display: block; width: 100%; padding: 16px; border-radius: 30px; text-decoration: none; font-weight: 700; font-size: 16px; margin: 12px 0; border: none; cursor: pointer; }
        .btn-primary { background: #f39c12; color: #0f172a; }
        .btn-secondary { background: rgba(255,255,255,0.1); color: #fff; }
        .stores { margin-top: 24px; }
        .hidden { display: none; }
    </style>
</head>
<body>
    <div class="card">
        <div class="icon">🎁</div>
        <h1>You have a Fretiko Gift Card</h1>
        <p>Tap the button to open the Fretiko app and claim it automatically.</p>
        <div class="code">${claimCode}</div>
        <a id="openApp" class="btn btn-primary" href="${appSchemeUrl}">Open in Fretiko App</a>
        <div id="stores" class="stores hidden">
            <p style="margin-top: 24px;">If the app didn't open, you may need to install it first:</p>
            <a class="btn btn-secondary" href="${playStoreUrl}">Get it on Google Play</a>
            <a class="btn btn-secondary" href="${appStoreUrl}">Download on the App Store</a>
            <p style="margin-top: 16px; font-size: 13px;">After installing, return to this email and tap "Open in Fretiko App" again.</p>
        </div>
    </div>

    <script>
        (function() {
            const openApp = document.getElementById('openApp');
            const stores = document.getElementById('stores');
            let hasBlurred = false;

            document.addEventListener('visibilitychange', function() {
                if (document.hidden) hasBlurred = true;
            });

            openApp.addEventListener('click', function(e) {
                e.preventDefault();
                hasBlurred = false;
                const now = Date.now();

                // Try to open the app via the custom scheme
                window.location.href = openApp.href;

                // After a short delay, if the page is still visible, the app is not installed
                setTimeout(function() {
                    if (!hasBlurred && Date.now() - now > 1500) {
                        stores.classList.remove('hidden');
                    }
                }, 2000);
            });
        })();
    </script>
</body>
</html>`;
  }
  
  async claimGiftCard(claimCode: string, userId: string): Promise<ClaimResponse> {
    this.logger.log(`Processing gift card claim for code ${claimCode} by user ${userId}`);
    
    // Find gift card by claim code
    const { data: giftCard, error } = await this.supabase
      .from('gift_cards')
      .select('*')
      .eq('claim_code', claimCode)
      .eq('status', 'active')
      .single();
    
    if (error || !giftCard) {
      throw new NotFoundException('Invalid or expired gift card');
    }
    
    // SECURITY: Validate that user is the intended recipient
    if (giftCard.recipient_user_id && giftCard.recipient_user_id !== userId) {
      throw new BadRequestException('This gift card is intended for someone else');
    }
    
    // If username was specified, validate that
    if (giftCard.recipient_username) {
      const { data: userProfile } = await this.supabase
        .from('user_profiles')
        .select('username')
        .eq('id', userId)
        .single();
      
      if (userProfile.username !== giftCard.recipient_username) {
        throw new BadRequestException('This gift card is intended for a different user');
      }
    }
    
    // Claim the gift card
    const { error: updateError } = await this.supabase
      .from('gift_cards')
      .update({
        status: 'claimed',
        recipient_user_id: userId,
        claimed_at: new Date().toISOString()
      })
      .eq('id', giftCard.id);
    
    if (updateError) {
      throw new BadRequestException('Failed to claim gift card');
    }

    // Update the associated chat message so all clients see the claimed state
    if (giftCard.chat_message_id) {
      try {
        await this.chatService.updateMessageMetadata(
          giftCard.chat_message_id,
          {
            status: 'claimed',
            claimedBy: userId,
            claimedAt: new Date().toISOString(),
          },
        );
      } catch (metadataError) {
        this.logger.error('Failed to update gift card chat message metadata:', metadataError);
        // Non-critical, gift card is already claimed
      }
    }
    
    // Log transaction
    await this.logTransaction(giftCard.id, 'claim', 0, giftCard.current_balance, userId);
    
    // Send notification to purchaser
    try {
      await this.notificationHelper.notifySystemUpdate(
        giftCard.purchaser_id,
        'Gift Card Claimed! ✅',
        `Your gift card was claimed`,
        { type: 'gift_card_claimed', giftCardId: giftCard.id }
      );
    } catch (error) {
      this.logger.error('Failed to send claim notification:', error);
      // Non-critical, continue with order
    }
    
    // Get updated gift card with design
    const { data: updatedGiftCard } = await this.supabase
      .from('gift_cards')
      .select(`
        *,
        design:gift_card_designs (
          name,
          design_url,
          preview_url
        )
      `)
      .eq('id', giftCard.id)
      .single();
    
    return {
      success: true,
      giftCard: {
        id: updatedGiftCard.id,
        cardNumber: updatedGiftCard.card_number,
        balance: updatedGiftCard.current_balance,
        design: updatedGiftCard.design
      }
    };
  }
  
  async applyToCheckout(
    cardNumber: string,
    pin: string,
    orderTotal: number,
    userId: string,
    requestedAmount?: number,
  ): Promise<RedeemResponse> {
    this.logger.log(`Applying gift card to checkout for user ${userId}`);
    
    // Validate gift card
    const { data: giftCard, error } = await this.supabase
      .from('gift_cards')
      .select('*')
      .eq('card_number', cardNumber)
      .eq('pin', pin)
      .in('status', ['active', 'claimed'])
      .single();
    
    if (error || !giftCard) {
      await this.incrementRedemptionAttempts(cardNumber);
      throw new BadRequestException('Invalid gift card or PIN');
    }
    
    // Check expiry
    if (giftCard.expires_at && new Date(giftCard.expires_at) < new Date()) {
      await this.expireGiftCard(giftCard.id);
      throw new BadRequestException('This gift card has expired');
    }
    
    // Calculate application amount. By default (no requestedAmount), use as much of the
    // card as possible, capped by the order total - this preserves existing behavior for
    // every caller that doesn't yet support a manual amount.
    const maxApplicable = Math.min(giftCard.current_balance, orderTotal);

    let appliedAmount = maxApplicable;
    if (requestedAmount !== undefined && requestedAmount !== null) {
      if (typeof requestedAmount !== 'number' || isNaN(requestedAmount) || requestedAmount <= 0) {
        throw new BadRequestException('Gift card amount must be a positive number');
      }
      // Round to 2 decimal places to avoid floating point drift, then clamp.
      const normalizedRequested = Math.round(requestedAmount * 100) / 100;
      if (normalizedRequested > maxApplicable + 0.001) {
        throw new BadRequestException(
          `Requested gift card amount (${normalizedRequested}) exceeds the maximum applicable amount (${maxApplicable})`
        );
      }
      appliedAmount = Math.min(normalizedRequested, maxApplicable);
    }
    
    if (appliedAmount <= 0) {
      throw new BadRequestException('Gift card has no remaining balance');
    }

    // ✅ FIX: Actually move real money for the gift card portion instead of
    // just decrementing the card's balance. Release the reserve from the
    // marketing wallet and hold it in the buyer's escrow balance, so the
    // order's escrow (created right after this call) is fully funded and
    // the vendor/rider/platform can be paid correctly.
    //
    // ✅ ATOMIC FIX: All of these movements are now wrapped in a single
    // Postgres RPC (redeem_gift_card_atomic). The card row is locked FOR
    // UPDATE, the reserve is debited, the buyer's escrow is held, the
    // card balance is decremented, and the audit row is inserted in one
    // transaction. This closes the previous double-spend window where
    // the wallet movements could commit but the card balance update could
    // fail.
    const reservationRef = randomUUID();

    const { data: redeemResult, error: redeemRpcError } = await this.supabase.rpc(
      'redeem_gift_card_atomic',
      {
        p_card_number: cardNumber,
        p_pin: pin,
        p_user_id: userId,
        p_admin_user_id: this.adminGiftWalletId,
        p_applied_amount: appliedAmount,
        p_order_id: null,
        p_user_ip: null,
        p_reservation_ref: reservationRef,
      }
    );

    if (redeemRpcError) {
      await this.incrementRedemptionAttempts(cardNumber);
      this.logger.error(`[GiftCardsService] redeem_gift_card_atomic RPC error: ${redeemRpcError.message}`);
      throw new BadRequestException(`Gift card cannot be applied right now: ${redeemRpcError.message}`);
    }

    if (!redeemResult || !redeemResult.success) {
      await this.incrementRedemptionAttempts(cardNumber);
      this.logger.error(`[GiftCardsService] redeem_gift_card_atomic returned failure: ${redeemResult?.error || 'Unknown'}`);
      throw new BadRequestException(redeemResult?.error || 'Gift card cannot be applied right now');
    }

    if (redeemResult.already_processed) {
      this.logger.warn(`[GiftCardsService] ⚠️ IDEMPOTENT: Duplicate gift card redemption detected and prevented for user ${userId}, reservation: ${reservationRef}`);
    } else {
      this.logger.log(`[GiftCardsService] ✅ Atomic gift card redemption successful: reservation ${reservationRef}, card ${redeemResult.gift_card_id}`);
    }

    // The RPC already inserted the gift_card_transactions row. We just
    // need its id for the response (subsequently used to link to the
    // order group). Fetch the latest transaction for this card, which is
    // guaranteed to be the one just created because the card was locked.
    const { data: transaction } = await this.supabase
      .from('gift_card_transactions')
      .select('id')
      .eq('gift_card_id', redeemResult.gift_card_id)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    return {
      appliedAmount: redeemResult.applied_amount,
      remainingBalance: redeemResult.remaining_balance,
      transactionId: transaction?.id || null,
    };
  }
  
  /**
   * Revert a gift card application made via applyToCheckout, e.g. when the
   * order that was supposed to use it fails to complete. Restores the
   * balance and status the card had before the application, and logs a
   * reversal transaction. Safe to call even if the order was never created
   * (transaction has no order_id yet).
   */
  /**
   * Revert a gift card redemption.
   *
   * ✅ ATOMIC FIX: All wallet movements, gift card balance/status update,
   * and admin_adjust audit row are now handled by
   * revert_gift_card_redemption_atomic() in one Postgres transaction.
   */
  async revertGiftCardApplication(transactionId: string, reason: string): Promise<void> {
    const { data: transaction, error: txError } = await this.supabase
      .from('gift_card_transactions')
      .select('*')
      .eq('id', transactionId)
      .eq('transaction_type', 'redeem')
      .single();

    if (txError || !transaction) {
      this.logger.error(`Cannot revert gift card application: transaction ${transactionId} not found`);
      return;
    }

    const revertAmount = Number(transaction.amount || 0);
    if (revertAmount <= 0) {
      this.logger.warn(`Nothing to revert for gift card transaction ${transactionId}`);
      return;
    }

    const { data: revertResult, error: revertRpcError } = await this.supabase.rpc(
      'revert_gift_card_redemption_atomic',
      {
        p_transaction_id: transactionId,
        p_amount: revertAmount,
        p_reason: reason,
        p_admin_gift_user_id: this.adminGiftWalletId,
      }
    );

    if (revertRpcError) {
      this.logger.error('revert_gift_card_redemption_atomic RPC error:', revertRpcError);
      return;
    }

    if (!revertResult || !revertResult.success) {
      this.logger.error(
        `Failed to revert gift card application ${transactionId}: ${revertResult?.error || 'Unknown error'}`
      );
      return;
    }

    this.logger.log(
      `Reverted gift card application ${transactionId}: restored ${revertResult.revert_amount} to card ${revertResult.gift_card_id} (new balance: ${revertResult.new_balance})`
    );
  }

  /**
   * Link a gift card redeem transaction to a multi-vendor order group. The
   * gift card is applied once for the whole group, so only the first created
   * order can be directly linked via order_id (a real FK). We also stash the
   * order_group_id in metadata so refundGiftCard can resolve the transaction
   * for ANY suborder in the group, not just the first one.
   */
  async linkTransactionToOrderGroup(transactionId: string, firstOrderId: string, orderGroupId: string): Promise<void> {
    try {
      const { data: transaction } = await this.supabase
        .from('gift_card_transactions')
        .select('metadata')
        .eq('id', transactionId)
        .single();

      await this.supabase
        .from('gift_card_transactions')
        .update({
          order_id: firstOrderId,
          metadata: { ...(transaction?.metadata || {}), order_group_id: orderGroupId },
        })
        .eq('id', transactionId);
    } catch (error) {
      this.logger.error(`Failed to link gift card transaction ${transactionId} to order group ${orderGroupId}:`, error);
      // Non-critical for order creation, but refunds for non-first suborders won't
      // resolve the gift card transaction if this fails - logged for investigation.
    }
  }

  async checkBalance(cardNumber: string, pin: string): Promise<BalanceResponse> {
    const { data: giftCard, error } = await this.supabase
      .from('gift_cards')
      .select('current_balance, expires_at, status')
      .eq('card_number', cardNumber)
      .eq('pin', pin)
      .single();
    
    if (error || !giftCard) {
      throw new BadRequestException('Invalid gift card or PIN');
    }
    
    return {
      balance: giftCard.current_balance,
      expiresAt: giftCard.expires_at,
      status: giftCard.status
    };
  }
  
  async getMyGiftCards(userId: string): Promise<any[]> {
    const { data, error } = await this.supabase
      .from('gift_cards')
      .select(`
        *,
        design:gift_card_designs (
          name,
          design_url,
          preview_url
        )
      `)
      .or(`purchaser_id.eq.${userId},recipient_user_id.eq.${userId}`)
      .order('created_at', { ascending: false });
    
    if (error) {
      throw new BadRequestException('Failed to fetch gift cards');
    }
    
    return data;
  }
  
  async refundGiftCard(orderId: string, amount: number, reason: string, orderGroupId?: string): Promise<void> {
    // Find the gift card transaction for this order. For orders that are part of a
    // multi-vendor group, only the first order in the group is directly linked via
    // order_id (the gift card is applied once for the whole group) - fall back to
    // looking the transaction up by order_group_id so any suborder in the group can
    // trigger a correctly-scoped partial refund.
    let { data: transaction } = await this.supabase
      .from('gift_card_transactions')
      .select('*')
      .eq('order_id', orderId)
      .eq('transaction_type', 'redeem')
      .single();

    if (!transaction && orderGroupId) {
      const { data: groupTransaction } = await this.supabase
        .from('gift_card_transactions')
        .select('*')
        .eq('transaction_type', 'redeem')
        .eq('metadata->>order_group_id', orderGroupId)
        .single();
      transaction = groupTransaction;
    }
    
    if (!transaction) {
      throw new NotFoundException('Gift card transaction not found for this order');
    }
    
    // ✅ ATOMIC FIX: All wallet movements, gift card balance/status update,
    // and audit log are now handled by revert_gift_card_redemption_atomic().
    const { data: revertResult, error: revertRpcError } = await this.supabase.rpc(
      'revert_gift_card_redemption_atomic',
      {
        p_transaction_id: transaction.id,
        p_amount: amount,
        p_reason: reason,
        p_admin_gift_user_id: this.adminGiftWalletId,
        p_order_id: orderId,
      }
    );

    if (revertRpcError) {
      this.logger.error('revert_gift_card_redemption_atomic RPC error:', revertRpcError);
      throw new Error(`Gift card refund failed: ${revertRpcError.message}`);
    }

    if (!revertResult || !revertResult.success) {
      throw new Error(`Gift card refund failed: ${revertResult?.error || 'Unknown error'}`);
    }
  }
  
  private async logTransaction(
    giftCardId: string,
    type: string,
    amount: number | null,
    balanceAfter: number,
    userId: string | null,
    metadata: any = {}
  ): Promise<any> {
    const { data, error } = await this.supabase
      .from('gift_card_transactions')
      .insert({
        gift_card_id: giftCardId,
        transaction_type: type,
        amount: amount,
        balance_after: balanceAfter,
        user_id: userId || null,
        metadata
      })
      .select()
      .single();
    
    if (error) {
      this.logger.error(`Failed to log gift card transaction: ${error.message}`);
    }
    
    return data;
  }
  
  private async incrementRedemptionAttempts(cardNumber: string): Promise<void> {
    await this.supabase.rpc('increment_redemption_attempts', { p_card_number: cardNumber });
  }
  
  private async expireGiftCard(giftCardId: string): Promise<void> {
    await this.supabase
      .from('gift_cards')
      .update({ status: 'expired' })
      .eq('id', giftCardId);
  }

  /**
   * Admin-only: Create gift cards for competitions, promotions, customer service
   * Debits the platform wallet and credits the marketing/gift reserve wallet
   * to back each card, so admin-issued cards don't consume the reserve that
   * backs user-purchased cards.
   */
  async adminCreateGiftCard(adminId: string, dto: AdminCreateGiftCardDto): Promise<GiftCard[]> {
    this.logger.log(`Admin ${adminId} creating ${dto.quantity || 1} gift card(s) for: ${dto.creation_reason}`);
    
    const quantity = dto.quantity || 1;
    const createdCards: GiftCard[] = [];
    
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + (dto.expiry_days || 365));
    
    // Create gift cards in batch
    // ✅ ATOMIC FIX: Each card is now created in a single Postgres transaction
    // by admin_create_gift_card_atomic().
    for (let i = 0; i < quantity; i++) {
      const { data: createResult, error: createRpcError } = await this.supabase.rpc(
        'admin_create_gift_card_atomic',
        {
          p_design_id: dto.design_id,
          p_initial_balance: dto.amount,
          p_admin_id: adminId,
          p_creation_reason: dto.creation_reason,
          p_is_commercial: dto.is_commercial || false,
          p_notes: dto.notes,
          p_expires_at: expiresAt.toISOString(),
          p_platform_wallet_id: this.platformWalletId,
          p_reserve_wallet_id: this.adminGiftWalletId,
        }
      );

      if (createRpcError) {
        this.logger.error('admin_create_gift_card_atomic RPC error:', createRpcError);
        this.logger.error(`Failed to create gift card ${i + 1}: ${createRpcError.message}`);
        continue;
      }

      if (!createResult || !createResult.success) {
        this.logger.error(
          `Failed to create gift card ${i + 1}: ${createResult?.error || 'Unknown error'}`
        );
        continue;
      }

      createdCards.push(createResult.gift_card as GiftCard);
    }
    
    this.logger.log(`Successfully created ${createdCards.length}/${quantity} gift cards`);
    
    if (createdCards.length === 0) {
      throw new BadRequestException('Failed to create any gift cards');
    }
    
    return createdCards;
  }

  /**
   * Admin: Get all gift cards with filtering and pagination
   */
  async getAllGiftCards(options: {
    status?: string;
    page: number;
    limit: number;
    search?: string;
  }) {
    const { status, page, limit, search } = options;
    
    let query = this.supabase
      .from('gift_cards')
      .select(`
        *,
        design:gift_card_designs (
          name,
          design_url,
          preview_url
        )
      `, { count: 'exact' });
    
    if (status && status !== 'all') {
      query = query.eq('status', status);
    }
    
    if (search) {
      query = query.or(`card_number.ilike.%${search}%,recipient_email.ilike.%${search}%,recipient_username.ilike.%${search}%`);
    }
    
    const from = (page - 1) * limit;
    const to = from + limit - 1;
    
    const { data, error, count } = await query
      .order('created_at', { ascending: false })
      .range(from, to);
    
    if (error) {
      throw new BadRequestException(`Failed to fetch gift cards: ${error.message}`);
    }
    
    return {
      data: data || [],
      total: count || 0,
      page,
      limit,
      totalPages: Math.ceil((count || 0) / limit)
    };
  }

  /**
   * Admin: Get gift card by ID
   */
  async getGiftCardById(id: string) {
    const { data, error } = await this.supabase
      .from('gift_cards')
      .select(`
        *,
        design:gift_card_designs (
          name,
          design_url,
          preview_url
        ),
        transactions:gift_card_transactions (
          transaction_type,
          amount,
          balance_after,
          created_at,
          metadata
        )
      `)
      .eq('id', id)
      .single();
    
    if (error) {
      throw new NotFoundException('Gift card not found');
    }
    
    return data;
  }

  /**
   * Admin: Block a gift card
   */
  async blockGiftCard(id: string, reason: string) {
    const { data: giftCard, error: fetchError } = await this.supabase
      .from('gift_cards')
      .select('*')
      .eq('id', id)
      .single();
    
    if (fetchError) {
      throw new NotFoundException('Gift card not found');
    }
    
    if (giftCard.status === 'blocked') {
      throw new BadRequestException('Gift card is already blocked');
    }
    
    const { error } = await this.supabase
      .from('gift_cards')
      .update({ status: 'blocked' })
      .eq('id', id);
    
    if (error) {
      throw new BadRequestException(`Failed to block gift card: ${error.message}`);
    }
    
    // Log transaction
    await this.logTransaction(id, 'block', null, giftCard.current_balance, null, {
      reason,
      previous_status: giftCard.status
    });
    
    return { success: true, message: 'Gift card blocked successfully' };
  }

  /**
   * Admin: Unblock a gift card
   */
  async unblockGiftCard(id: string) {
    const { data: giftCard, error: fetchError } = await this.supabase
      .from('gift_cards')
      .select('*')
      .eq('id', id)
      .single();
    
    if (fetchError) {
      throw new NotFoundException('Gift card not found');
    }
    
    if (giftCard.status !== 'blocked') {
      throw new BadRequestException('Gift card is not blocked');
    }
    
    // Restore previous status (default to 'active' if uncertain)
    const previousStatus = giftCard.metadata?.previous_status || 'active';
    
    const { error } = await this.supabase
      .from('gift_cards')
      .update({ status: previousStatus })
      .eq('id', id);
    
    if (error) {
      throw new BadRequestException(`Failed to unblock gift card: ${error.message}`);
    }
    
    // Log transaction
    await this.logTransaction(id, 'admin_adjust', null, giftCard.current_balance, null, {
      action: 'unblock',
      restored_status: previousStatus
    });
    
    return { success: true, message: 'Gift card unblocked successfully' };
  }

  /**
   * Admin: Get gift card statistics
   */
  async getGiftCardStats() {
    const { data: cards, error } = await this.supabase
      .from('gift_cards')
      .select('status, initial_balance, current_balance, created_at');
    
    if (error) {
      throw new BadRequestException(`Failed to fetch statistics: ${error.message}`);
    }
    
    const stats = {
      total_issued: cards.length,
      total_redeemed: cards.filter(c => c.status === 'redeemed').length,
      total_active: cards.filter(c => c.status === 'active' || c.status === 'claimed').length,
      total_expired: cards.filter(c => c.status === 'expired').length,
      total_blocked: cards.filter(c => c.status === 'blocked').length,
      total_value_issued: cards.reduce((sum, c) => sum + Number(c.initial_balance), 0),
      total_value_redeemed: cards.filter(c => c.status === 'redeemed').reduce((sum, c) => sum + (Number(c.initial_balance) - Number(c.current_balance)), 0),
      total_value_active: cards.filter(c => c.status === 'active' || c.status === 'claimed').reduce((sum, c) => sum + Number(c.current_balance), 0),
      redemption_rate: 0,
      breakage_rate: 0,
      period_revenue: 0
    };
    
    // Calculate rates
    if (stats.total_issued > 0) {
      stats.redemption_rate = (stats.total_redeemed / stats.total_issued) * 100;
      stats.breakage_rate = (stats.total_expired / stats.total_issued) * 100;
    }
    
    // Calculate period revenue (last 30 days)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    
    const recentCards = cards.filter(c => new Date(c.created_at) >= thirtyDaysAgo);
    stats.period_revenue = recentCards.reduce((sum, c) => sum + Number(c.initial_balance), 0);
    
    return stats;
  }

  /**
   * Admin: Get gift card analytics
   */
  async getGiftCardAnalytics(period: string = '30d') {
    const days = period === '7d' ? 7 : period === '90d' ? 90 : 30;
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);
    
    const { data: cards, error } = await this.supabase
      .from('gift_cards')
      .select('status, initial_balance, current_balance, created_at, expires_at')
      .gte('created_at', startDate.toISOString());
    
    if (error) {
      throw new BadRequestException(`Failed to fetch analytics: ${error.message}`);
    }
    
    // Group by day
    const dailyData = {};
    cards.forEach(card => {
      const day = new Date(card.created_at).toISOString().split('T')[0];
      if (!dailyData[day]) {
        dailyData[day] = { issued: 0, redeemed: 0, value: 0 };
      }
      dailyData[day].issued++;
      dailyData[day].value += Number(card.initial_balance);
      if (card.status === 'redeemed') {
        dailyData[day].redeemed++;
      }
    });
    
    return {
      period,
      days,
      dailyData,
      totalCards: cards.length,
      totalValue: cards.reduce((sum, c) => sum + Number(c.initial_balance), 0),
      redemptionRate: cards.length > 0 ? (cards.filter(c => c.status === 'redeemed').length / cards.length) * 100 : 0
    };
  }

  /**
   * Admin: Get all gift card designs
   */
  async getGiftCardDesigns() {
    const { data, error } = await this.supabase
      .from('gift_card_designs')
      .select('*')
      .order('sort_order', { ascending: true });
    
    if (error) {
      throw new BadRequestException(`Failed to fetch designs: ${error.message}`);
    }
    
    return data;
  }

  /**
   * Admin: Create a new gift card design
   */
  async createGiftCardDesign(body: {
    name: string;
    design_url: string;
    preview_url: string;
    is_active?: boolean;
    sort_order?: number;
  }) {
    const { data, error } = await this.supabase
      .from('gift_card_designs')
      .insert({
        name: body.name,
        design_url: body.design_url,
        preview_url: body.preview_url,
        is_active: body.is_active !== undefined ? body.is_active : true,
        sort_order: body.sort_order || 0
      })
      .select()
      .single();
    
    if (error) {
      throw new BadRequestException(`Failed to create design: ${error.message}`);
    }
    
    return data;
  }

  /**
   * Admin: Update a gift card design
   */
  async updateGiftCardDesign(id: string, body: {
    name?: string;
    design_url?: string;
    preview_url?: string;
    is_active?: boolean;
    sort_order?: number;
  }) {
    const { data, error } = await this.supabase
      .from('gift_card_designs')
      .update(body)
      .eq('id', id)
      .select()
      .single();
    
    if (error) {
      throw new BadRequestException(`Failed to update design: ${error.message}`);
    }
    
    return data;
  }

  /**
   * Admin: Delete a gift card design
   */
  async deleteGiftCardDesign(id: string) {
    // Check if design is in use
    const { data: inUse } = await this.supabase
      .from('gift_cards')
      .select('id')
      .eq('design_id', id)
      .limit(1);
    
    if (inUse && inUse.length > 0) {
      throw new BadRequestException('Cannot delete design that is in use by existing gift cards');
    }
    
    const { error } = await this.supabase
      .from('gift_card_designs')
      .delete()
      .eq('id', id);
    
    if (error) {
      throw new BadRequestException(`Failed to delete design: ${error.message}`);
    }
    
    return { success: true, message: 'Design deleted successfully' };
  }

  /**
   * Admin: Get gift card settings
   */
  async getGiftCardSettings() {
    // For now, return default settings. In production, this would be stored in a settings table
    return {
      min_amount: 1,
      max_amount: 10000,
      default_expiry_days: 365,
      max_quantity_per_purchase: 10,
      allowed_delivery_methods: ['email', 'chat', 'both']
    };
  }

  /**
   * Admin: Update gift card settings
   */
  async updateGiftCardSettings(body: {
    min_amount?: number;
    max_amount?: number;
    default_expiry_days?: number;
    max_quantity_per_purchase?: number;
  }) {
    // For now, just return the updated settings. In production, this would update a settings table
    const currentSettings = await this.getGiftCardSettings();
    const updatedSettings = { ...currentSettings, ...body };
    
    return updatedSettings;
  }

  /**
   * Admin: Upload gift card design image to Supabase Storage
   */
  async uploadDesignImage(adminId: string, file: any): Promise<{
    url: string;
    fileData: {
      name: string;
      size: number;
      type: string;
      mimeType: string;
    };
  }> {
    const BUCKET_NAME = 'gift-card-designs'; // Create this bucket in Supabase Storage
    const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

    if (file.size > MAX_FILE_SIZE) {
      throw new BadRequestException('File too large. Maximum size is 10MB');
    }

    if (!file.mimetype || !file.mimetype.startsWith('image/')) {
      throw new BadRequestException('Only image files are allowed for gift card designs');
    }

    try {
      // Generate unique filename
      const fileExtension = file.originalname ? file.originalname.split('.').pop() : 'png';
      const uniqueFileName = `${adminId}/${Date.now()}_${Math.random().toString(36).substring(2)}.${fileExtension}`;

      // Upload file to Supabase Storage
      const { data: uploadData, error: uploadError } = await this.supabase.storage
        .from(BUCKET_NAME)
        .upload(uniqueFileName, file.buffer, {
          contentType: file.mimetype,
          upsert: false,
        });

      if (uploadError) {
        this.logger.error('Gift card design upload failed:', uploadError);
        throw new BadRequestException(`Upload failed: ${uploadError.message}`);
      }

      // Get public URL
      const { data: urlData } = this.supabase.storage
        .from(BUCKET_NAME)
        .getPublicUrl(uniqueFileName);

      return {
        url: urlData.publicUrl,
        fileData: {
          name: file.originalname,
          size: file.size,
          type: 'image',
          mimeType: file.mimetype,
        },
      };
    } catch (error) {
      this.logger.error('Gift card design upload error:', error);
      throw error;
    }
  }

  /**
   * Admin: Get marketing (platform gift) wallet balance
   */
  async getMarketingWalletBalance() {
    const wallet = await this.walletService.getWallet(this.adminGiftWalletId);
    return {
      userId: this.adminGiftWalletId,
      availableBalance: wallet.availableBalance,
      escrowBalance: wallet.escrowBalance,
      pendingWithdrawal: wallet.pendingWithdrawal,
      totalValue: wallet.availableBalance + wallet.escrowBalance + wallet.pendingWithdrawal,
    };
  }

  /**
   * Admin: Get marketing wallet recent transactions
   */
  async getMarketingWalletTransactions(options: { page?: number; limit?: number } = {}) {
    const page = options.page || 1;
    const limit = options.limit || 20;
    const offset = (page - 1) * limit;

    const { data, error, count } = await this.supabase
      .from('wallet_ledger')
      .select('*', { count: 'estimated' })
      .eq('user_id', this.adminGiftWalletId)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (error) {
      this.logger.error('Failed to fetch marketing wallet transactions:', error);
      throw new BadRequestException('Failed to fetch marketing wallet transactions');
    }

    return {
      data: data || [],
      total: count || 0,
      page,
      limit,
    };
  }

  /**
   * Get public claim status of a gift card by claim code.
   */
  async getClaimStatus(claimCode: string, userId: string) {
    const { data: giftCard, error } = await this.supabase
      .from('gift_cards')
      .select('claim_code, status, recipient_user_id, purchaser_id, claimed_at')
      .eq('claim_code', claimCode)
      .single();

    if (error || !giftCard) {
      throw new NotFoundException('Gift card not found');
    }

    const isClaimed = giftCard.status === 'claimed' || giftCard.status === 'redeemed';
    const isClaimedByMe = isClaimed && giftCard.recipient_user_id === userId;
    const isRecipient = giftCard.recipient_user_id === userId;

    return {
      claimCode: giftCard.claim_code,
      status: giftCard.status,
      claimedBy: isClaimed ? giftCard.recipient_user_id : undefined,
      claimedAt: isClaimed ? giftCard.claimed_at : undefined,
      isClaimed,
      isClaimedByMe,
      isRecipient,
    };
  }
}
