-- =====================================================
-- Migration: 184
-- Add purchase_gift_card_atomic(): a single RPC that atomically
-- creates a gift card, debits the buyer, funds the reserve wallet,
-- and logs the purchase transaction.
--
-- Background (the bug this fixes):
--   gift-cards.service.ts purchaseGiftCard() currently does:
--     1. processWalletTransaction('gift_card_purchase', -amount) - debit buyer
--     2. INSERT INTO gift_cards (card created by DB triggers)
--     3. processWalletTransaction('gift_card_purchase', +amount) - credit reserve
--     4. logTransaction('purchase', ...) - audit row
--   Steps 2-4 happen after the buyer's wallet has been debited.
--   If the reserve credit or gift_cards insert fails, the buyer is
--   charged but the card is either not created or not backed by
--   reserve funds. The existing code marks this as CRITICAL and
--   requires manual reconciliation.
--
-- What this migration does:
--   Adds purchase_gift_card_atomic(), which in one Postgres
--   transaction:
--     1. Debits the buyer's wallet for the gift card amount.
--     2. Treats an idempotent debit as "already processed" and
--       returns the existing gift card (looked up by reference).
--     3. Inserts the gift_cards row (card_number, pin, claim_code
--       generated automatically by the existing triggers).
--     4. Credits the admin/marketing reserve wallet.
--     5. Inserts the gift_card_transactions audit row.
--   If any step fails, the entire transaction rolls back, so the
--   buyer is never charged without a created, reserve-backed card.
--
--   This is additive only and does not modify the existing
--   process_wallet_transaction or gift card tables.
-- =====================================================

BEGIN;

CREATE OR REPLACE FUNCTION purchase_gift_card_atomic(
  p_purchaser_id UUID,
  p_admin_user_id UUID,
  p_amount NUMERIC,
  p_design_id UUID,
  p_recipient_user_id UUID DEFAULT NULL,
  p_recipient_username TEXT DEFAULT NULL,
  p_recipient_email TEXT DEFAULT NULL,
  p_recipient_phone TEXT DEFAULT NULL,
  p_delivery_method TEXT DEFAULT 'none',
  p_expires_at TIMESTAMPTZ DEFAULT NULL,
  p_purchase_ip TEXT DEFAULT NULL,
  p_reference_id TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_debit_result RECORD;
  v_reserve_result RECORD;
  v_gift_card RECORD;
  v_reference TEXT;
  v_existing_gift_card RECORD;
BEGIN
  -- 1. Validate inputs.
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Gift card amount must be positive',
      'error_code', 'INVALID_AMOUNT'
    );
  END IF;

  v_reference := COALESCE(p_reference_id, gen_random_uuid()::TEXT);

  -- 2. Debit the buyer. process_wallet_transaction locks the wallet
  --    and is idempotent for (user_id, transaction_type, reference_type,
  --    reference_id).
  SELECT * INTO v_debit_result
  FROM process_wallet_transaction(
    p_purchaser_id,
    'gift_card_purchase',
    -p_amount,
    'Gift card purchase',
    v_reference,
    'gift_card_purchase'
  );

  IF NOT v_debit_result.success THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', v_debit_result.error_message,
      'error_code', 'DEBIT_FAILED'
    );
  END IF;

  -- 3. If the buyer's ledger row already exists for this reference,
  --    the whole purchase was already committed. Find and return the
  --    existing card instead of creating a duplicate.
  IF v_debit_result.idempotent THEN
    SELECT gc.*, d.name, d.design_url, d.preview_url
    INTO v_existing_gift_card
    FROM gift_cards gc
    LEFT JOIN gift_card_designs d ON d.id = gc.design_id
    WHERE gc.purchaser_id = p_purchaser_id
      AND gc.initial_balance = p_amount
      AND gc.recipient_user_id IS NOT DISTINCT FROM p_recipient_user_id
    ORDER BY gc.created_at DESC
    LIMIT 1;

    IF FOUND THEN
      RETURN jsonb_build_object(
        'success', true,
        'already_processed', true,
        'transaction_id', v_debit_result.transaction_id,
        'gift_card', to_jsonb(v_existing_gift_card)
      );
    END IF;

    -- Should not happen, but safe fallback.
    RETURN jsonb_build_object(
      'success', true,
      'already_processed', true,
      'transaction_id', v_debit_result.transaction_id
    );
  END IF;

  -- 4. Insert the gift card. card_number, pin, and claim_code are
  --    generated by the existing set_gift_card_defaults() trigger.
  INSERT INTO gift_cards (
    purchaser_id,
    design_id,
    initial_balance,
    current_balance,
    status,
    recipient_user_id,
    recipient_username,
    recipient_email,
    recipient_phone,
    delivery_method,
    expires_at,
    purchase_ip,
    source,
    metadata
  )
  VALUES (
    p_purchaser_id,
    p_design_id,
    p_amount,
    p_amount,
    'active',
    p_recipient_user_id,
    p_recipient_username,
    p_recipient_email,
    p_recipient_phone,
    p_delivery_method,
    p_expires_at,
    p_purchase_ip,
    'user_purchase',
    p_metadata
  )
  RETURNING * INTO v_gift_card;

  -- 5. Credit the admin/marketing reserve wallet. Same transaction,
  --    so a failure rolls back the buyer's debit and the gift_cards
  --    insert.
  SELECT * INTO v_reserve_result
  FROM process_wallet_transaction(
    p_admin_user_id,
    'gift_card_purchase',
    p_amount,
    'Reserve funding for gift card purchase',
    v_gift_card.id::TEXT,
    'gift_card_reserve'
  );

  IF NOT v_reserve_result.success THEN
    RAISE EXCEPTION 'Reserve wallet credit failed for gift card %: %', v_gift_card.id, v_reserve_result.error_message;
  END IF;

  -- 6. Log the purchase transaction.
  INSERT INTO gift_card_transactions (
    gift_card_id,
    transaction_type,
    amount,
    balance_after,
    user_id,
    user_ip,
    metadata
  )
  VALUES (
    v_gift_card.id,
    'purchase',
    p_amount,
    p_amount,
    p_purchaser_id,
    p_purchase_ip,
    jsonb_build_object(
      'debit_transaction_id', v_debit_result.transaction_id,
      'reserve_credit_transaction_id', v_reserve_result.transaction_id,
      'reference_id', v_reference
    ) || p_metadata
  );

  RETURN jsonb_build_object(
    'success', true,
    'already_processed', false,
    'transaction_id', v_debit_result.transaction_id,
    'reserve_transaction_id', v_reserve_result.transaction_id,
    'gift_card', to_jsonb(v_gift_card)
  );

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'Error in purchase_gift_card_atomic: %', SQLERRM;
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Internal error during gift card purchase',
      'error_code', 'INTERNAL_ERROR',
      'error_message', SQLERRM
    );
END;
$$;

COMMENT ON FUNCTION purchase_gift_card_atomic IS
'Atomically purchases a gift card: debits buyer, inserts the gift_cards row (card_number/pin/claim_code generated by triggers), credits the admin/marketing reserve wallet, and logs a gift_card_transactions row in one Postgres transaction. Uses the buyer ledger row as the idempotency marker. Returns the created gift_card record as JSONB.';

REVOKE ALL ON FUNCTION purchase_gift_card_atomic(UUID, UUID, NUMERIC, UUID, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION purchase_gift_card_atomic(UUID, UUID, NUMERIC, UUID, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, JSONB) FROM anon;
REVOKE ALL ON FUNCTION purchase_gift_card_atomic(UUID, UUID, NUMERIC, UUID, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, JSONB) FROM authenticated;
GRANT EXECUTE ON FUNCTION purchase_gift_card_atomic(UUID, UUID, NUMERIC, UUID, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, JSONB) TO service_role;
ALTER FUNCTION purchase_gift_card_atomic(UUID, UUID, NUMERIC, UUID, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, JSONB) SET search_path = public, pg_temp;

COMMIT;

-- =====================================================
-- Verification (run manually after applying):
--
--   select has_function_privilege('service_role', 'purchase_gift_card_atomic(uuid,uuid,numeric,uuid,uuid,text,text,text,text,timestamptz,text,text,jsonb)', 'EXECUTE') as service_role_can_call,
--          has_function_privilege('authenticated', 'purchase_gift_card_atomic(uuid,uuid,numeric,uuid,uuid,text,text,text,text,timestamptz,text,text,jsonb)', 'EXECUTE') as authenticated_can_call;
--
-- Expected: service_role_can_call = true, authenticated_can_call = false.
--
-- Next step: replace the multi-call sequence in
-- GiftCardsService.purchaseGiftCard() with a single call to this RPC.
-- =====================================================
