import { Injectable, Logger, BadRequestException, NotFoundException, ForbiddenException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createServiceSupabaseClient } from '../shared/supabase.client';
import {
  CreateReportDto,
  UpdateReportDto,
  ReviewReportDto,
  ReportResponseDto,
  ReportListFilterDto,
  ReportStatsDto,
  ReportVisibility,
  ReportStatus,
  ReportPriority,
  ReportType,
} from './dto/report.dto';

/**
 * Reports Service
 * Internal reporting system for staff
 */
@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);
  private supabase;

  constructor(private configService: ConfigService) {
    this.supabase = createServiceSupabaseClient(this.configService);
  }

  /**
   * Create a new report
   */
  async createReport(staffId: string, reportDto: CreateReportDto): Promise<ReportResponseDto> {
    // Get staff details
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, full_name, department_id')
      .eq('id', staffId)
      .single();

    if (!staff) {
      throw new BadRequestException('Staff not found');
    }

    // Create report (report_number is auto-generated by trigger)
    const { data: report, error } = await this.supabase
      .from('reports')
      .insert({
        title: reportDto.title,
        report_type: reportDto.reportType,
        content: reportDto.content,
        data: reportDto.data || {},
        created_by: staffId,
        department_id: staff.department_id,
        visibility: reportDto.visibility || ReportVisibility.DEPARTMENT,
        status: ReportStatus.DRAFT,
        priority: reportDto.priority || ReportPriority.NORMAL,
        attachments: reportDto.attachments || [],
        tags: reportDto.tags || [],
      })
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to create report: ${error.message}`);
      throw new BadRequestException('Failed to create report');
    }

    this.logger.log(`Report created: ${report.report_number} by ${staff.full_name}`);

    return this.mapToResponseDto(report);
  }

  /**
   * Get all reports (filtered by permissions)
   */
  async getReports(staffId: string, filters?: ReportListFilterDto): Promise<ReportResponseDto[]> {
    // Get staff details
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, department_id, role')
      .eq('id', staffId)
      .single();

    if (!staff) {
      throw new NotFoundException('Staff not found');
    }

    let query = this.supabase
      .from('reports')
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name),
        reviewer:staff_accounts!reviewed_by(id, full_name)
      `)
      .order('created_at', { ascending: false });

    // Filter based on role
    if (staff.role !== 'super_admin') {
      if (staff.role === 'department_head') {
        // Department heads see:
        // 1. Their own reports
        // 2. Department reports
        // 3. Escalated reports
        query = query.or(
          `created_by.eq.${staffId},and(visibility.eq.department,department_id.eq.${staff.department_id}),visibility.eq.escalated,visibility.eq.all`
        );
      } else {
        // Regular staff see:
        // 1. Their own reports
        // 2. All-visibility reports
        query = query.or(`created_by.eq.${staffId},visibility.eq.all`);
      }
    }
    // Super admin sees all

    // Apply filters
    if (filters?.reportType) {
      query = query.eq('report_type', filters.reportType);
    }

    if (filters?.status) {
      query = query.eq('status', filters.status);
    }

    if (filters?.visibility) {
      query = query.eq('visibility', filters.visibility);
    }

    if (filters?.priority) {
      query = query.eq('priority', filters.priority);
    }

    if (filters?.createdBy) {
      query = query.eq('created_by', filters.createdBy);
    }

    if (filters?.departmentId) {
      query = query.eq('department_id', filters.departmentId);
    }

    if (filters?.search) {
      query = query.or(`title.ilike.%${filters.search}%,content.ilike.%${filters.search}%`);
    }

    if (filters?.tag) {
      query = query.contains('tags', [filters.tag]);
    }

    const { data: reports, error } = await query;

    if (error) {
      this.logger.error(`Failed to fetch reports: ${error.message}`);
      throw new BadRequestException('Failed to fetch reports');
    }

    return reports.map(report => this.mapToResponseDto(report));
  }

  /**
   * Get report by ID
   */
  async getReportById(reportId: string, staffId: string): Promise<ReportResponseDto> {
    const { data: report, error } = await this.supabase
      .from('reports')
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name),
        reviewer:staff_accounts!reviewed_by(id, full_name)
      `)
      .eq('id', reportId)
      .single();

    if (error || !report) {
      throw new NotFoundException('Report not found');
    }

    // Verify staff has access to this report
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, department_id, role')
      .eq('id', staffId)
      .single();

    const hasAccess =
      report.created_by === staffId || // Created by this staff
      report.visibility === ReportVisibility.ALL || // All-visibility
      staff.role === 'super_admin' || // Super admin sees all
      (report.visibility === ReportVisibility.ESCALATED && staff.role === 'super_admin') || // Escalated reports for super admin
      (report.visibility === ReportVisibility.DEPARTMENT && report.department_id === staff.department_id); // Department reports

    if (!hasAccess) {
      throw new ForbiddenException('Access denied to this report');
    }

    return this.mapToResponseDto(report);
  }

  /**
   * Update report (only draft reports can be updated)
   */
  async updateReport(reportId: string, staffId: string, updateDto: UpdateReportDto): Promise<ReportResponseDto> {
    // Get report
    const { data: report } = await this.supabase
      .from('reports')
      .select('id, created_by, status')
      .eq('id', reportId)
      .single();

    if (!report) {
      throw new NotFoundException('Report not found');
    }

    // Only creator can update
    if (report.created_by !== staffId) {
      throw new ForbiddenException('Only the creator can update this report');
    }

    // Only draft reports can be updated
    if (report.status !== ReportStatus.DRAFT) {
      throw new BadRequestException('Only draft reports can be updated');
    }

    const updateData: any = {};

    if (updateDto.title) updateData.title = updateDto.title;
    if (updateDto.reportType) updateData.report_type = updateDto.reportType;
    if (updateDto.content) updateData.content = updateDto.content;
    if (updateDto.data) updateData.data = updateDto.data;
    if (updateDto.visibility) updateData.visibility = updateDto.visibility;
    if (updateDto.priority) updateData.priority = updateDto.priority;
    if (updateDto.attachments) updateData.attachments = updateDto.attachments;
    if (updateDto.tags) updateData.tags = updateDto.tags;

    const { data: updatedReport, error } = await this.supabase
      .from('reports')
      .update(updateData)
      .eq('id', reportId)
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to update report: ${error.message}`);
      throw new BadRequestException('Failed to update report');
    }

    this.logger.log(`Report updated: ${updatedReport.report_number}`);

    return this.mapToResponseDto(updatedReport);
  }

  /**
   * Submit report (change from draft to submitted)
   */
  async submitReport(reportId: string, staffId: string): Promise<ReportResponseDto> {
    // Get report
    const { data: report } = await this.supabase
      .from('reports')
      .select('id, created_by, status')
      .eq('id', reportId)
      .single();

    if (!report) {
      throw new NotFoundException('Report not found');
    }

    // Only creator can submit
    if (report.created_by !== staffId) {
      throw new ForbiddenException('Only the creator can submit this report');
    }

    // Only draft reports can be submitted
    if (report.status !== ReportStatus.DRAFT) {
      throw new BadRequestException('Only draft reports can be submitted');
    }

    const { data: updatedReport, error } = await this.supabase
      .from('reports')
      .update({ status: ReportStatus.SUBMITTED })
      .eq('id', reportId)
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to submit report: ${error.message}`);
      throw new BadRequestException('Failed to submit report');
    }

    this.logger.log(`Report submitted: ${updatedReport.report_number}`);

    return this.mapToResponseDto(updatedReport);
  }

  /**
   * Review report (department heads and super admin)
   */
  async reviewReport(reportId: string, staffId: string, reviewDto: ReviewReportDto): Promise<ReportResponseDto> {
    // Get staff details
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, role, department_id')
      .eq('id', staffId)
      .single();

    // Get report
    const { data: report } = await this.supabase
      .from('reports')
      .select('id, department_id, status')
      .eq('id', reportId)
      .single();

    if (!report) {
      throw new NotFoundException('Report not found');
    }

    // Only submitted or under_review reports can be reviewed
    if (![ReportStatus.SUBMITTED, ReportStatus.UNDER_REVIEW].includes(report.status as ReportStatus)) {
      throw new BadRequestException('Only submitted or under-review reports can be reviewed');
    }

    // Check permissions: department head can review their department reports, super admin can review all
    const canReview =
      staff.role === 'super_admin' ||
      (staff.role === 'department_head' && staff.department_id === report.department_id);

    if (!canReview) {
      throw new ForbiddenException('You do not have permission to review this report');
    }

    const { data: updatedReport, error } = await this.supabase
      .from('reports')
      .update({
        status: reviewDto.status,
        reviewed_by: staffId,
        reviewed_at: new Date().toISOString(),
        review_notes: reviewDto.reviewNotes || null,
      })
      .eq('id', reportId)
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name),
        reviewer:staff_accounts!reviewed_by(id, full_name)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to review report: ${error.message}`);
      throw new BadRequestException('Failed to review report');
    }

    this.logger.log(`Report reviewed: ${updatedReport.report_number} by ${staff.id}`);

    return this.mapToResponseDto(updatedReport);
  }

  /**
   * Escalate report to super admin
   */
  async escalateReport(reportId: string, staffId: string): Promise<ReportResponseDto> {
    // Get report
    const { data: report } = await this.supabase
      .from('reports')
      .select('id, created_by, visibility')
      .eq('id', reportId)
      .single();

    if (!report) {
      throw new NotFoundException('Report not found');
    }

    // Only creator can escalate
    if (report.created_by !== staffId) {
      throw new ForbiddenException('Only the creator can escalate this report');
    }

    // Change visibility to escalated
    const { data: updatedReport, error } = await this.supabase
      .from('reports')
      .update({ visibility: ReportVisibility.ESCALATED })
      .eq('id', reportId)
      .select(`
        *,
        creator:staff_accounts!created_by(id, full_name),
        department:departments!department_id(id, name)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to escalate report: ${error.message}`);
      throw new BadRequestException('Failed to escalate report');
    }

    this.logger.log(`Report escalated: ${updatedReport.report_number}`);

    return this.mapToResponseDto(updatedReport);
  }

  /**
   * Get report statistics
   */
  async getReportStats(staffId: string): Promise<ReportStatsDto> {
    // Get staff details
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, department_id, role')
      .eq('id', staffId)
      .single();

    let query = this.supabase
      .from('reports')
      .select('id, status, report_type, priority, visibility, created_by, department_id');

    // Filter based on role
    if (staff.role !== 'super_admin') {
      if (staff.role === 'department_head') {
        query = query.or(
          `created_by.eq.${staffId},and(visibility.eq.department,department_id.eq.${staff.department_id}),visibility.eq.escalated,visibility.eq.all`
        );
      } else {
        query = query.or(`created_by.eq.${staffId},visibility.eq.all`);
      }
    }

    const { data: reports } = await query;

    const total = reports?.length || 0;

    const byStatus = {
      draft: reports?.filter(r => r.status === ReportStatus.DRAFT).length || 0,
      submitted: reports?.filter(r => r.status === ReportStatus.SUBMITTED).length || 0,
      under_review: reports?.filter(r => r.status === ReportStatus.UNDER_REVIEW).length || 0,
      reviewed: reports?.filter(r => r.status === ReportStatus.REVIEWED).length || 0,
      archived: reports?.filter(r => r.status === ReportStatus.ARCHIVED).length || 0,
    };

    const byType = {
      incident: reports?.filter(r => r.report_type === ReportType.INCIDENT).length || 0,
      performance: reports?.filter(r => r.report_type === ReportType.PERFORMANCE).length || 0,
      financial: reports?.filter(r => r.report_type === ReportType.FINANCIAL).length || 0,
      user_activity: reports?.filter(r => r.report_type === ReportType.USER_ACTIVITY).length || 0,
      operational: reports?.filter(r => r.report_type === ReportType.OPERATIONAL).length || 0,
      other: reports?.filter(r => r.report_type === ReportType.OTHER).length || 0,
    };

    const byPriority = {
      low: reports?.filter(r => r.priority === ReportPriority.LOW).length || 0,
      normal: reports?.filter(r => r.priority === ReportPriority.NORMAL).length || 0,
      high: reports?.filter(r => r.priority === ReportPriority.HIGH).length || 0,
      critical: reports?.filter(r => r.priority === ReportPriority.CRITICAL).length || 0,
    };

    const pendingReview = reports?.filter(r =>
      r.status === ReportStatus.SUBMITTED || r.status === ReportStatus.UNDER_REVIEW
    ).length || 0;

    return {
      total,
      byStatus,
      byType,
      byPriority,
      pendingReview,
    };
  }

  /**
   * Map database record to response DTO
   */
  private mapToResponseDto(report: any): ReportResponseDto {
    return {
      id: report.id,
      reportNumber: report.report_number,
      title: report.title,
      reportType: report.report_type,
      content: report.content,
      data: report.data || {},
      createdBy: report.created_by,
      createdByName: report.creator?.full_name || 'Unknown',
      departmentId: report.department_id,
      departmentName: report.department?.name,
      visibility: report.visibility,
      status: report.status,
      priority: report.priority,
      reviewedBy: report.reviewed_by,
      reviewedByName: report.reviewer?.full_name,
      reviewedAt: report.reviewed_at,
      reviewNotes: report.review_notes,
      attachments: report.attachments || [],
      tags: report.tags || [],
      createdAt: report.created_at,
      updatedAt: report.updated_at,
      submittedAt: report.submitted_at,
    };
  }
}
