import { Injectable, Logger, UnauthorizedException, BadRequestException, NotFoundException, ConflictException, Inject, forwardRef } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcrypt';
import { createServiceSupabaseClient } from '../shared/supabase.client';
import { AuditService } from '../audit/audit.service';
import { AuditAction, AuditEntityType, AuditStatus } from '../audit/dto/audit.dto';
import {
  StaffLoginDto,
  CreateStaffDto,
  UpdateStaffDto,
  UpdateMyProfileDto,
  ChangePasswordDto,
  StaffResponseDto,
  StaffLoginResponseDto,
  StaffRole,
} from './dto/staff.dto';

/**
 * Staff Service
 * Manages internal tool staff accounts, authentication, and permissions
 */
@Injectable()
export class StaffService {
  private readonly logger = new Logger(StaffService.name);
  private supabase;

  constructor(
    private jwtService: JwtService,
    private configService: ConfigService,
    @Inject(forwardRef(() => AuditService))
    private auditService: AuditService,
  ) {
    this.supabase = createServiceSupabaseClient(this.configService);
  }

  /**
   * Staff login with staff_id or email + password
   * Uses custom JWT tokens generated by NestJS JwtService
   * 
   * Flow:
   * 1. Find staff account in staff_accounts table
   * 2. Verify password against staff_accounts.password_hash (bcrypt)
   * 3. Generate custom JWT tokens (access + refresh)
   * 4. Update last login timestamp
   * 5. Return JWT tokens and staff info
   */
  async login(loginDto: StaffLoginDto): Promise<StaffLoginResponseDto> {
    const { staffIdOrEmail, password } = loginDto;

    // Find staff by staff_id or email (don't filter by is_active yet - we need to check status)
    const { data: staff, error } = await this.supabase
      .from('staff_accounts')
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .or(`staff_id.eq.${staffIdOrEmail},email.eq.${staffIdOrEmail}`)
      .maybeSingle(); // Use maybeSingle to avoid throwing on no rows

    if (error) {
      this.logger.warn(`Database error during login for: ${staffIdOrEmail}`, error);
      throw new UnauthorizedException('Invalid credentials');
    }

    if (!staff) {
      this.logger.warn(`Failed login attempt for: ${staffIdOrEmail} - Staff not found`);
      throw new UnauthorizedException('Invalid credentials');
    }

    // Check if account is deleted (terminated)
    if (staff.deleted_at) {
      this.logger.warn(`Login attempt for terminated staff: ${staff.staff_id} (${staff.email})`);
      throw new UnauthorizedException('Staff employment was terminated');
    }

    // Check if account is suspended
    if (staff.is_suspended) {
      this.logger.warn(`Login attempt for suspended staff: ${staff.staff_id} (${staff.email})`);
      throw new UnauthorizedException('Staff account suspended');
    }

    // Check if account is active
    if (!staff.is_active) {
      this.logger.warn(`Login attempt for inactive staff: ${staff.staff_id} (${staff.email})`);
      throw new UnauthorizedException('Staff account is inactive');
    }

    // Verify password
    const isPasswordValid = await bcrypt.compare(password, staff.password_hash);
    if (!isPasswordValid) {
      this.logger.warn(`Invalid password for staff: ${staff.staff_id}`);
      throw new UnauthorizedException('Invalid credentials');
    }

    // Generate JWT tokens
    const payload = {
      sub: staff.id,
      staffId: staff.staff_id,
      email: staff.email,
      role: staff.role,
      departmentId: staff.department_id,
    };

    const accessToken = this.jwtService.sign(payload, { expiresIn: '8h' });
    const refreshToken = this.jwtService.sign(payload, { expiresIn: '7d' });

    // Update last login
    await this.supabase
      .from('staff_accounts')
      .update({ last_login_at: new Date().toISOString() })
      .eq('id', staff.id);

    this.logger.log(`Staff logged in: ${staff.staff_id} (${staff.email})`);

    return {
      accessToken,
      refreshToken,
      staff: this.mapToResponseDto(staff),
    };
  }

  /**
   * Create a new staff account
   * Requires super_admin or HR with create_staff permission
   * 
   * Creates staff account directly in staff_accounts table
   * Generates a UUID for the staff account ID
   */
  async createStaff(createDto: CreateStaffDto, createdBy: string): Promise<StaffResponseDto> {
    // Hash password for staff_accounts table
    const passwordHash = await bcrypt.hash(createDto.password, 10);

    // Verify department exists if provided
    if (createDto.departmentId) {
      const { data: dept, error } = await this.supabase
        .from('departments')
        .select('id')
        .eq('id', createDto.departmentId)
        .single();

      if (error || !dept) {
        throw new BadRequestException('Invalid department ID');
      }
    }

    // Check if email already exists
    const { data: existingStaff } = await this.supabase
      .from('staff_accounts')
      .select('id')
      .eq('email', createDto.email)
      .single();

    if (existingStaff) {
      throw new ConflictException('Email already exists');
    }

    // Generate next staff_id
    const { data: lastStaff } = await this.supabase
      .from('staff_accounts')
      .select('staff_id')
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    let nextStaffId = 'FTK-2025-0001';
    if (lastStaff?.staff_id) {
      const match = lastStaff.staff_id.match(/FTK-(\d+)-(\d+)/);
      if (match) {
        const year = parseInt(match[1]);
        const num = parseInt(match[2]);
        const currentYear = new Date().getFullYear();
        if (year === currentYear) {
          nextStaffId = `FTK-${currentYear}-${String(num + 1).padStart(4, '0')}`;
        } else {
          nextStaffId = `FTK-${currentYear}-0001`;
        }
      }
    }

    // Create staff account (let database generate UUID for id)
    const { data: newStaff, error } = await this.supabase
      .from('staff_accounts')
      .insert({
        staff_id: nextStaffId,
        email: createDto.email,
        password_hash: passwordHash,
        full_name: createDto.fullName,
        department_id: createDto.departmentId || null,
        role: createDto.role,
        created_by: createdBy,
        must_change_password: true,
      })
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to create staff: ${error.message}`);
      throw new BadRequestException('Failed to create staff account');
    }

    this.logger.log(`Staff created: ${newStaff.staff_id} by ${createdBy}`);

    return this.mapToResponseDto(newStaff);
  }

  /**
   * Get all staff (filtered by permissions)
   */
  async getAllStaff(requestingStaffId: string): Promise<StaffResponseDto[]> {
    const { data: requestingStaff } = await this.supabase
      .from('staff_accounts')
      .select('role, department_id')
      .eq('id', requestingStaffId)
      .single();

    let query = this.supabase
      .from('staff_accounts')
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .order('created_at', { ascending: false });

    // Filter based on role
    if (requestingStaff.role === 'department_head') {
      // Department heads can only see staff in their department
      query = query.eq('department_id', requestingStaff.department_id);
    }
    // Super admin sees all

    const { data: staff, error } = await query;

    if (error) {
      this.logger.error(`Failed to fetch staff: ${error.message}`);
      throw new BadRequestException('Failed to fetch staff');
    }

    return staff.map(s => this.mapToResponseDto(s));
  }

  /**
   * Get staff by ID
   */
  async getStaffById(staffId: string, includeDeleted: boolean = false): Promise<StaffResponseDto> {
    let query = this.supabase
      .from('staff_accounts')
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .eq('id', staffId);

    if (!includeDeleted) {
      query = query.is('deleted_at', null);
    }

    const { data: staff, error } = await query.single();

    if (error || !staff) {
      throw new NotFoundException('Staff not found');
    }

    return this.mapToResponseDto(staff);
  }

  /**
   * Update own profile
   * Allows staff to update their own fullName and email
   */
  async updateMyProfile(staffId: string, updateDto: UpdateMyProfileDto): Promise<StaffResponseDto> {
    // Check if email is being changed and if it already exists
    if (updateDto.email) {
      const { data: existingStaff } = await this.supabase
        .from('staff_accounts')
        .select('id')
        .eq('email', updateDto.email)
        .neq('id', staffId)
        .single();

      if (existingStaff) {
        throw new ConflictException('Email already exists');
      }
    }

    const updateData: any = {};

    if (updateDto.fullName) updateData.full_name = updateDto.fullName;
    if (updateDto.email) updateData.email = updateDto.email;

    // Only update if there's something to update
    if (Object.keys(updateData).length === 0) {
      throw new BadRequestException('No fields to update');
    }

    const { data: updatedStaff, error } = await this.supabase
      .from('staff_accounts')
      .update(updateData)
      .eq('id', staffId)
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to update profile: ${error.message}`);
      throw new BadRequestException('Failed to update profile');
    }

    this.logger.log(`Profile updated: ${updatedStaff.staff_id}`);

    return this.mapToResponseDto(updatedStaff);
  }

  /**
   * Update staff account
   * Requires permissions (for admins to update other staff)
   */
  async updateStaff(staffId: string, updateDto: UpdateStaffDto): Promise<StaffResponseDto> {
    const updateData: any = {};

    if (updateDto.fullName) updateData.full_name = updateDto.fullName;
    if (updateDto.departmentId !== undefined) updateData.department_id = updateDto.departmentId;
    if (updateDto.role) updateData.role = updateDto.role;
    if (updateDto.isActive !== undefined) updateData.is_active = updateDto.isActive;

    const { data: updatedStaff, error } = await this.supabase
      .from('staff_accounts')
      .update(updateData)
      .eq('id', staffId)
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to update staff: ${error.message}`);
      throw new BadRequestException('Failed to update staff');
    }

    this.logger.log(`Staff updated: ${updatedStaff.staff_id}`);

    return this.mapToResponseDto(updatedStaff);
  }

  /**
   * Change staff password
   */
  async changePassword(staffId: string, changePasswordDto: ChangePasswordDto): Promise<{ message: string }> {
    const { currentPassword, newPassword } = changePasswordDto;

    // Get current staff with email
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, email, password_hash')
      .eq('id', staffId)
      .single();

    if (!staff) {
      throw new NotFoundException('Staff not found');
    }

    // Verify current password against staff_accounts
    const isPasswordValid = await bcrypt.compare(currentPassword, staff.password_hash);
    if (!isPasswordValid) {
      throw new UnauthorizedException('Current password is incorrect');
    }

    // Hash new password for staff_accounts
    const newPasswordHash = await bcrypt.hash(newPassword, 10);

    // Update password in staff_accounts
    const { error: updateError } = await this.supabase
      .from('staff_accounts')
      .update({
        password_hash: newPasswordHash,
        password_changed_at: new Date().toISOString(),
        must_change_password: false,
      })
      .eq('id', staffId);

    if (updateError) {
      this.logger.error(`Failed to update password in staff_accounts: ${updateError.message}`);
      throw new BadRequestException('Failed to change password');
    }

    this.logger.log(`Password changed for staff ID: ${staffId}`);

    return { message: 'Password changed successfully' };
  }

  /**
   * Deactivate staff account
   */
  async deactivateStaff(staffId: string): Promise<{ message: string }> {
    const { error } = await this.supabase
      .from('staff_accounts')
      .update({ is_active: false })
      .eq('id', staffId);

    if (error) {
      this.logger.error(`Failed to deactivate staff: ${error.message}`);
      throw new BadRequestException('Failed to deactivate staff');
    }

    this.logger.log(`Staff deactivated: ${staffId}`);

    return { message: 'Staff deactivated successfully' };
  }

  /**
   * Suspend staff account
   * Used for temporary suspensions (investigations, disciplinary actions)
   */
  async suspendStaff(
    targetStaffId: string,
    suspendedBy: string,
    reason?: string,
  ): Promise<{ message: string }> {
    this.logger.log(`Attempting to suspend staff: ${targetStaffId} by ${suspendedBy}`);
    
    // Check if staff exists and is not already suspended
    // Don't filter by deleted_at - we should be able to suspend even if they're marked as deleted
    const { data: staff, error: staffError } = await this.supabase
      .from('staff_accounts')
      .select('id, staff_id, full_name, is_suspended, role, deleted_at')
      .eq('id', targetStaffId)
      .maybeSingle(); // Use maybeSingle() instead of single() to avoid throwing on no rows

    if (staffError) {
      this.logger.error(`Database error finding staff for suspension: ${staffError.message}`, {
        targetStaffId,
        suspendedBy,
        error: staffError,
      });
      throw new NotFoundException(`Staff not found: ${staffError.message}`);
    }

    if (!staff) {
      this.logger.error(`Staff not found for ID: ${targetStaffId}`, {
        targetStaffId,
        suspendedBy,
      });
      throw new NotFoundException(`Staff not found with ID: ${targetStaffId}`);
    }

    this.logger.log(`Found staff to suspend: ${staff.staff_id} (${staff.full_name}), role: ${staff.role}`);

    if (staff.is_suspended) {
      throw new BadRequestException('Staff is already suspended');
    }

    // Prevent suspending super admins (unless by another super admin)
    if (staff.role === 'super_admin') {
      const { data: suspender } = await this.supabase
        .from('staff_accounts')
        .select('role')
        .eq('id', suspendedBy)
        .single();

      if (suspender?.role !== 'super_admin') {
        throw new BadRequestException('Only super admins can suspend other super admins');
      }
    }

    // Prevent self-suspension
    if (targetStaffId === suspendedBy) {
      throw new BadRequestException('You cannot suspend yourself');
    }

    const { error } = await this.supabase
      .from('staff_accounts')
      .update({
        is_suspended: true,
        suspended_at: new Date().toISOString(),
        suspended_by: suspendedBy,
        suspension_reason: reason || 'Suspended by admin',
        is_active: false, // Also deactivate when suspended
      })
      .eq('id', targetStaffId);

    if (error) {
      this.logger.error(`Failed to suspend staff: ${error.message}`);
      throw new BadRequestException('Failed to suspend staff');
    }

    this.logger.log(`Staff suspended: ${targetStaffId} by ${suspendedBy}`);

    // Log audit action (don't let audit failure break the suspension)
    try {
      await this.auditService.logAction({
        staffId: suspendedBy,
        action: AuditAction.EDIT_STAFF,
        entityType: AuditEntityType.STAFF,
        entityId: targetStaffId,
        details: {
          action: 'suspend_staff',
          targetStaffId,
          targetStaffName: staff.full_name,
          reason: reason || 'Suspended by admin',
        },
        status: AuditStatus.SUCCESS,
      });
    } catch (auditError) {
      this.logger.warn(`Failed to log audit for staff suspension: ${auditError.message}`);
      // Don't throw - audit logging failure shouldn't break the suspension
    }

    return { message: 'Staff suspended successfully' };
  }

  /**
   * Unsuspend staff account
   * Restores access after suspension period
   */
  async unsuspendStaff(targetStaffId: string, unsuspendedBy: string): Promise<{ message: string }> {
    // Check if staff exists and is suspended
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, staff_id, is_suspended')
      .eq('id', targetStaffId)
      .single();

    if (!staff) {
      throw new NotFoundException('Staff not found');
    }

    if (!staff.is_suspended) {
      throw new BadRequestException('Staff is not suspended');
    }

    const { error } = await this.supabase
      .from('staff_accounts')
      .update({
        is_suspended: false,
        suspended_at: null,
        suspended_by: null,
        suspension_reason: null,
        is_active: true, // Reactivate when unsuspended
      })
      .eq('id', targetStaffId);

    if (error) {
      this.logger.error(`Failed to unsuspend staff: ${error.message}`);
      throw new BadRequestException('Failed to unsuspend staff');
    }

    this.logger.log(`Staff unsuspended: ${targetStaffId} by ${unsuspendedBy}`);

    // Log audit action
    await this.auditService.logAction({
      staffId: unsuspendedBy,
      action: AuditAction.EDIT_STAFF,
      entityType: AuditEntityType.STAFF,
      entityId: targetStaffId,
      details: {
        action: 'unsuspend_staff',
        targetStaffId,
        targetStaffName: staff.staff_id,
      },
      status: AuditStatus.SUCCESS,
    });

    return { message: 'Staff unsuspended successfully' };
  }

  /**
   * Delete staff account (permanent removal)
   * Used when staff is sacked/terminated
   * This is a soft delete (sets deleted_at) for audit purposes
   */
  async deleteStaff(
    targetStaffId: string,
    deletedBy: string,
    reason?: string,
  ): Promise<{ message: string }> {
    // Check if staff exists
    const { data: staff } = await this.supabase
      .from('staff_accounts')
      .select('id, staff_id, full_name, role, deleted_at')
      .eq('id', targetStaffId)
      .single();

    if (!staff) {
      throw new NotFoundException('Staff not found');
    }

    if (staff.deleted_at) {
      throw new BadRequestException('Staff is already deleted');
    }

    // Prevent deleting super admins (unless by another super admin)
    if (staff.role === 'super_admin') {
      const { data: deleter } = await this.supabase
        .from('staff_accounts')
        .select('role')
        .eq('id', deletedBy)
        .single();

      if (deleter?.role !== 'super_admin') {
        throw new BadRequestException('Only super admins can delete other super admins');
      }
    }

    // Prevent self-deletion
    if (targetStaffId === deletedBy) {
      throw new BadRequestException('You cannot delete yourself');
    }

    // Soft delete: set deleted_at and deactivate
    const { error } = await this.supabase
      .from('staff_accounts')
      .update({
        deleted_at: new Date().toISOString(),
        is_active: false,
        is_suspended: false, // Clear suspension if any
        suspended_at: null,
        suspended_by: null,
        suspension_reason: reason || 'Account deleted by admin',
      })
      .eq('id', targetStaffId);

    if (error) {
      this.logger.error(`Failed to delete staff: ${error.message}`);
      throw new BadRequestException('Failed to delete staff');
    }

    this.logger.log(`Staff deleted: ${targetStaffId} by ${deletedBy}`);

    // Log audit action
    await this.auditService.logAction({
      staffId: deletedBy,
      action: AuditAction.DELETE_STAFF,
      entityType: AuditEntityType.STAFF,
      entityId: targetStaffId,
      details: {
        action: 'delete_staff',
        targetStaffId,
        targetStaffName: staff.full_name,
        reason: reason || 'Account deleted by admin',
      },
      status: AuditStatus.SUCCESS,
    });

    return { message: 'Staff deleted successfully' };
  }

  /**
   * Initialize super admin account
   * Creates the first super admin account (one-time operation)
   */
  async initializeSuperAdmin(email: string, password: string, fullName: string): Promise<StaffResponseDto> {
    const passwordHash = await bcrypt.hash(password, 10);

    // Check if super admin already exists
    const { data: existing } = await this.supabase
      .from('staff_accounts')
      .select('id')
      .eq('email', email)
      .single();

    if (existing) {
      throw new ConflictException('Super admin already exists');
    }

    // Create super admin account (let database generate UUID for id)
    const { data: superAdmin, error } = await this.supabase
      .from('staff_accounts')
      .insert({
        staff_id: 'FTK-2025-0001',
        email,
        password_hash: passwordHash,
        full_name: fullName,
        department_id: null,
        role: StaffRole.SUPER_ADMIN,
        is_active: true,
        must_change_password: true,
        created_by: null,
      })
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .single();

    if (error) {
      this.logger.error(`Failed to initialize super admin: ${error.message}`);
      throw new BadRequestException('Failed to initialize super admin');
    }

    this.logger.log('Super admin initialized successfully');

    return this.mapToResponseDto(superAdmin);
  }

  /**
   * Upload profile picture
   */
  async uploadAvatar(staffId: string, file: Express.Multer.File): Promise<StaffResponseDto> {
    if (!file) {
      throw new BadRequestException('No file provided');
    }

    // Validate file type
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    if (!allowedTypes.includes(file.mimetype)) {
      throw new BadRequestException('Invalid file type. Only JPEG, PNG, and WebP images are allowed.');
    }

    // Validate file size (max 5MB)
    const maxSize = 5 * 1024 * 1024; // 5MB
    if (file.size > maxSize) {
      throw new BadRequestException('File too large. Maximum size is 5MB.');
    }

    // Get current staff to check if they have an existing avatar
    const { data: currentStaff } = await this.supabase
      .from('staff_accounts')
      .select('avatar_url')
      .eq('id', staffId)
      .single();

    // Generate unique filename
    const fileExtension = file.originalname.split('.').pop() || 'jpg';
    const timestamp = Date.now();
    const uniqueFileName = `staff/${staffId}/${timestamp}-avatar.${fileExtension}`;

    // Upload to Supabase Storage
    const { data: uploadData, error: uploadError } = await this.supabase.storage
      .from('media')
      .upload(uniqueFileName, file.buffer, {
        contentType: file.mimetype,
        upsert: false,
      });

    if (uploadError) {
      this.logger.error(`Failed to upload avatar: ${uploadError.message}`);
      throw new BadRequestException(`Upload failed: ${uploadError.message}`);
    }

    // Get public URL
    const { data: urlData } = this.supabase.storage
      .from('media')
      .getPublicUrl(uniqueFileName);

    const avatarUrl = urlData.publicUrl;

    // Delete old avatar if it exists
    if (currentStaff?.avatar_url) {
      try {
        // Extract path from URL
        const oldPath = currentStaff.avatar_url.split('/media/')[1];
        if (oldPath) {
          await this.supabase.storage
            .from('media')
            .remove([oldPath]);
        }
      } catch (error) {
        // Log but don't fail if old avatar deletion fails
        this.logger.warn(`Failed to delete old avatar: ${error}`);
      }
    }

    // Update staff account with new avatar URL
    const { data: updatedStaff, error: updateError } = await this.supabase
      .from('staff_accounts')
      .update({ avatar_url: avatarUrl })
      .eq('id', staffId)
      .select(`
        *,
        department:departments(id, name, slug, permissions)
      `)
      .single();

    if (updateError) {
      this.logger.error(`Failed to update avatar URL: ${updateError.message}`);
      throw new BadRequestException('Failed to update avatar URL');
    }

    this.logger.log(`Avatar uploaded for staff: ${updatedStaff.staff_id}`);

    return this.mapToResponseDto(updatedStaff);
  }

  /**
   * Map database record to response DTO
   */
  private mapToResponseDto(staff: any): StaffResponseDto {
    return {
      id: staff.id,
      staffId: staff.staff_id,
      email: staff.email,
      fullName: staff.full_name,
      departmentId: staff.department_id,
      departmentName: staff.department?.name,
      departmentPermissions: staff.department?.permissions || [],
      role: staff.role,
      isActive: staff.is_active,
      lastLoginAt: staff.last_login_at,
      mustChangePassword: staff.must_change_password,
      createdAt: staff.created_at,
      updatedAt: staff.updated_at,
      isSuspended: staff.is_suspended || false,
      suspendedAt: staff.suspended_at || null,
      suspendedBy: staff.suspended_by || null,
      suspensionReason: staff.suspension_reason || null,
      deletedAt: staff.deleted_at || null,
      avatarUrl: staff.avatar_url || null,
    };
  }
}
